version: "3.9"

services:
  backend:
    image: ohksj77/owori
    container_name: owori-backend
    ports:
      - 8080:8080
    networks:
      - app-tier
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: on-failure
    tty: true

  db:
    image: mysql
    container_name: owori-db
    ports:
      - 3306:3306
    networks:
      - app-tier
    volumes:
      - data_mysql:/var/lib/mysql
    environment:
      TZ: ${DATABASE_TIMEZONE}
      MYSQL_PORT: ${DATABASE_PORT}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_SCHEMA}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_HOST: ${DATABASE_HOST}
    restart: on-failure
    tty: true

  nginx:
    image: ohksj77/owori-nginx
    container_name: owori-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-tier
    restart: on-failure
    tty: true

networks:
  app-tier:
    driver: bridge

volumes:
  data_mysql: null
