version: "3"

services:
  backend:
    build:
      context: .
    platform: linux/amd64
    container_name: owori-backend
    ports:
      - 8080:8080
    networks:
      - app-tier
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: on-failure
    tty: true

  nginx:
    build: ./nginx
    platform: linux/amd64
    container_name: owori-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-tier
    restart: always
    tty: true

networks:
  app-tier:
    driver: bridge

volumes:
  data_mysql: null
