version: "3"

services:
  backend:
    build:
      context: .
    platform: linux/amd64
    container_name: owori-backend
    ports:
      - 8080:8080
    networks:
      - app-tier
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: on-failure
    tty: true

  db:
    image: mysql
    container_name: owori-db
    platform: linux/amd64
    ports:
      - 3306:3306
    networks:
      - app-tier
    volumes:
      - data_mysql:/var/lib/mysql
    env_file:
      - .env
    restart: on-failure
    tty: true

  nginx:
    build: ./nginx
    platform: linux/amd64
    container_name: owori-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-tier
    restart: on-failure
    tty: true

networks:
  app-tier:
    driver: bridge

volumes:
  data_mysql: null
