server:
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  config:
    import: classpath:env.yml

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  main:
    allow-bean-definition-overriding: true
