server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /api/v1

spring:
  config:
    import:
      - classpath:env.yml
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  main:
    allow-bean-definition-overriding: true
