server:
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://owori-db.ckkvly7j7buu.ap-northeast-2.rds.amazonaws.com:3306/owori?serverTimezone=Asia/Seoul
    username: owori

  config:
    import: classpath:env.yml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  main:
    allow-bean-definition-overriding: true
