name: Owori Backend CI
on:
  push:
    paths:
      - '**.java'
  pull_request:
    paths:
      - '**.java'
defaults:
  run:
    shell: bash
    working-directory: .
jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        architecture: x64

    - name: Set ENV
      run: |
        mkdir -p src/main/resources
        echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/env.yml
        find src
        
    - run: chmod +x gradlew
    - run: ./gradlew build

    - name: Test Coverage Report
      id: jacoco
      uses: madrapps/jacoco-report@v1.2
      with:
        paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "테스트 커버리지 측정"
        min-coverage-overall: 50
        min-coverage-changed-files: 50
